#!/bin/sh

set -e

case "$1" in
    configure)
	#if there is no folder, we create it
	[ -d "/etc/folder2ram" ] || mkdir "/etc/folder2ram"
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument" >&2
        exit 1
    ;;
esac

exit 0
