#!/bin/sh

set -e

case "$1" in
    configure)
	#if there is no folder, we create it
	[ -d "/etc/folder2ram" ] || mkdir "/etc/folder2ram"
	
	#generating the config file
    cat << EOF > "/etc/folder2ram/folder2ram.conf" 
#############################
#folder2ram main config file#
#############################
#
#PROTIP: to make /var/lock or /tmp available as ram filesystems, 
#        it is preferable to set the variables RAMTMP, RAMLOCK
#        in /etc/default/tmpfs.
#
#FILE SYSTEM: only option available is tmpfs, for now
#
#OPTIONS: does nothing, will be implemented in the future.
#
#<file system>  <mount point>   <options>
#tmpfs            /var/log        -     <---example entry

EOF
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument" >&2
        exit 1
    ;;
esac

exit 0
