#! /bin/sh

# Author:
#
#     Alberto Bursi <starshipeleven@hotmail.it>
#
# Copyright:
#
#     Alberto Bursi 2015
#
# License:
#
#     This program is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     This package is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# On Debian systems, the complete text of the GNU General
# Public License version 3 can be found in `/usr/share/common-licenses/GPL-3'.


#This script is HEAVILY commented, for the sake of easy understanding and mainteneance
#Don't think I'm patronizing, it's first and foremost because I'm sure I will forget 
#some of its arcane spells and I don't feel like wasting hours trying to understand what 
#I wrote an unspecified amount of time ago. -Alberto Bursi

#If you edit it, please comment HEAVILY what you are doing, you will thank me later.

############### USER INTERFACE FUNCTIONS

print_usage() {
	echo "folder2ram is a script-based utility that relocates the contents of a folder to RAM"
	echo "and on shutdown unmounts it safely synching the data back to the permanent storage."
	echo ""
	echo "There are five main components of folder2ram system:"
	echo "--the init scripts that do the mounting and unmounting automatically in /etc/init.d"
	echo "--the configuration and management tool in /etc/sbin/folder2ram"
	echo "--the configuration file in /etc/folder2ram/folder2ram.conf"
	echo "--the template files in /etc/folder2ram/templates"
	echo "--the folders in /var/folder2ram, the bind-mounted folders"
	echo "  they allow easy access to the original folder in permanent storage"
	echo "  since if you mount folder A on folder B you lose access to folder B"
	echo "  this trick allows access to B, allowing synching with the tmpfs at will"
	echo ""
	echo "for first startup use -configure action, then -generate, then -mountall"
	echo ""
	echo "list of actions:"
	echo ""
	echo "-generate"
	echo "::::::::::folder2ram will read the configuration file at /etc/folder2ram/folder2ram.etc"
	echo "::::::::::and generate the init scripts that are missing"
	echo ""
	echo "-clean"
	echo "::::::::::stop folder2ram and remove all folder2ram init scripts"
	echo ""
	echo "-refresh"
	echo "::::::::::execute a -clean followed by a -generate"
	echo ""
	echo "-status"
	echo "::::::::::print all mountpoints and their status (mounted or unmounted)"
	echo ""
	echo "-mount /folder/path"
	echo "::::::::::folder2ram will start the init script for that particular folder,"
	echo "::::::::::if it is in the configuration file."
	echo ""
	echo "-mountall"
	echo "::::::::::folder2ram will start all initscripts of all folders in the config file"
	echo ""
	echo "-umount /folder/path"
	echo "::::::::::folder2ram will stop the init script for that particular folder,"
	echo "::::::::::if it is in the configuration file."
	echo ""
	echo "-umountall"
	echo "::::::::::folder2ram will stop all initscripts of all folders in the config file"
	echo ""
	echo "-configure"
	echo "::::::::::folder2ram will open the configuration file in a text editor"
	echo ""
	echo "-reset"
	echo "::::::::::delete all folder2ram init scripts and restore default config file"
	echo ""
}

print_usage_exit() {
    print_usage
    exit
}

#################### UTILITY FUNCTIONS CALLED BY PRIMARY FUNCTIONS

read_mount_point() {
# this reads config file at a predetemined line and extracts mount point 
# $line_number must come from outside
# blank lines and commented lines are ignored, so line_number refers only to actual mount points
# a similar function can be used to extract additional options in the future

line_number=$1 

# get variable form outside, remove blank and commented lines, and print line at $line_number
mount_point=$( awk -v line="$line_number" '!/^ *#/ && NF == line {print $1}' "/etc/folder2ram/folder2ram.conf" )

# checking if mount point variable is empty, and if it is returning a keyword
if [ "x$mount_point" != "x" ]; then 
echo "$mount_point";
else
echo "no_more_mount_points";
fi

}

generate_initscript_name() {

# cleaning the mount point string to generate a initscript name that won't break anything
# basically turning /this/is/a/path into -this-is-a-path-mount_type

#initializing variables
mount_point=$1

# mount_type is hardcoded for now, will be set by something else when I implement more folder2ram options
mount_type="tmpfs" 

# field separator is set as "/" then the record separator is set as "-" , the loop prints one by one the fields
# (because I could not find a better way to get the damn "-" to be inserted properly) 
# then disables the record separators and prints the variable "mount_type" coming from outside awk (see the -v option)
clean_mount_point=$(echo "$mount_point" | awk -v mount_type="$mount_type" -F '/' '{ORS="-"; out=$1; for(i=1;i<=NF;i++){out=$i; print out}; ORS=""; print mount_type}' )

# generating the initscript name, will look like this "folder2ram-this-is-a-path-mount_type"
initscript_name="f2r$clean_mount_point"

#outputting the result
echo "$initscript_name"

}




########################## PRIMARY FUNCTIONS ################################

mount_umount_all() {

# initializing variables    
line_number=1 
start_or_stop=$1

######################CHECKING IF THERE ARE STILL MOUNT POINTS

# calling another function (above) to fill the mount point at this line number
mount_point=$(read_mount_point "$line_number")

#########################################################

############BEGINNING MAIN LOOP::::::::::::::::::::::::::::::::::::::

until [ "$mount_point" = "no_more_mount_points" ] ;  do

# calling another function (above) to fill the mount point at this line number
mount_point=$(read_mount_point "$line_number")

initscript_name=$(generate_initscript_name "$mount_point")

# generating a variable with full name inside, easier to manipulate
initscript_path="/etc/init.d/$initscript_name"

################FUNCTION PAYLOAD#############

if [ -e "initscript_path" ]; then 
echo "$initscript_path" "$start_or_stop" >> "/run/print_status";
"$initscript_path" "$start_or_stop"
else
echo "no folder2ram init script found" >> "/run/print_status";
fi


####################################

# increasing line number
line_number=$((line_number+1))

######################CHECKING IF THERE ARE STILL MOUNT POINTS

# calling another function (above) to fill the mount point at this line number
mount_point=$(read_mount_point "$line_number")

#########################################################

#:::::::::::ENDING OF MAIN LOOP
done

exit
}

mount_umount_mountpoint() {

# initializing variables    
specified_mount_point=$1
start_or_stop=$2

initscript_name=$(generate_initscript_name "$specified_mount_point")

# generating a variable with full name inside, easier to manipulate
initscript_path="/etc/init.d/$initscript_name"

################FUNCTION PAYLOAD#############

if [ -e "$initscript_path" ]; 
then ############BEGIN THEN

	echo "$initscript_path exists, starting" >> "/run/print_status";
	#starting or stopping the init script
	"$initscript_path" "$start_or_stop";

else ############BEGIN ELSE

	echo "$initscript_path not found, please add it to the config with -configure then do a -generate, then you can try again with this action" >> "/run/print_status";
fi

exit

}

generate_initscripts() {

# initializing variables    
line_number=1

######################CHECKING IF THERE ARE STILL MOUNT POINTS

# calling another function (above) to fill the mount point at this line number
mount_point=$(read_mount_point "$line_number")

#########################################################

############BEGINNING MAIN LOOP::::::::::::::::::::::::::::::::::::::

until [ "$mount_point" = "no_more_mount_points" ] ;  do

# calling another function (above) to fill the mount point at this line number
mount_point=$(read_mount_point "$line_number")

# calling another function (above) to fill the initscript name at this line number
initscript_name=$(generate_initscript_name "$mount_point")

# generating a variable with full name inside, easier to manipulate
initscript_path="/etc/init.d/$initscript_name"

###################BEGIN IF CHECK FOR SAME NAME SCRIPTS

#checking if there is another initscript with the same name, skipping to next mount point if found 
if [ -e "$initscript_path" ]; 
then ############BEGIN THEN

	echo "$initscript_path exists, skipping" >> "/run/print_status";

else ############BEGIN ELSE

	echo "generating $initscript_path";

# this reads the etc/folder2ram/templates/folder2ram_init_template
# and writes that into /etc/init.d/$initscript_name.
	cat "/etc/folder2ram/templates/folder2ram_init_template" >> "$initscript_path" ;

# this sets some variables we need to be different in the initscript, by appending them to the same file
	sed -i "/# Provides: folder2ram/c\# Provides: $initscript_name" "$initscript_path" ;
	sed -i "/NAME=name/c\NAME=$initscript_name" "$initscript_path" ;
	sed -i "/DIR=dir/c\DIR=$mount_point" "$initscript_path" ;

# this marks the newly created file as executable
	chmod +x "$initscript_path" ;

# this asks insserv to generate symlinks in the appropriate runlevels
	insserv "$initscript_name" ;

########END IF CHECK FOR SAME NAME SCRIPT
fi

# increasing line number
line_number=$((line_number+1))

################CHECKING IF THERE ARE STILL MOUNT POINTS

# calling another function (above) to fill the mount point at this line number
mount_point=$(read_mount_point "$line_number")

########################################################

#:::::::::::ENDING OF MAIN LOOP
done

exit
}


clean_initscripts() {

#calling a main function to unmount all folder2ram mounts before removal
mount_umount_all stop

# initializing variables    
line_number=1

######################CHECKING IF THERE ARE STILL MOUNT POINTS

# calling another function (above) to fill the mount point at this line number
mount_point=$(read_mount_point "$line_number")

#########################################################

############BEGINNING MAIN LOOP::::::::::::::::::::::::::::::::::::::

until [ "$mount_point" = "no_more_mount_points" ] ;  do

# calling another function (above) to fill the mount point at this line number
mount_point=$(read_mount_point "$line_number")

# calling another function (above) to fill the initscript name at this line number
initscript_name=$(generate_initscript_name "$mount_point")

# generating a variable with full name inside, easier to manipulate
initscript_path="/etc/init.d/$initscript_name"

###################BEGIN IF

#checking if there is an initscript with the same name, skipping to next mount point if found 
if [ -e "$initscript_path" ]; 
then ############BEGIN THEN

	echo "deleting $initscript_path" >> "/run/print_status";
	"$initscript_path" stop;
	insserv -r "$initscript_name";
	rm -f "$initscript_path";

else ############BEGIN ELSE and END THEN

	echo "$initscript_path not found, already deleted perhaps?" >> "/run/print_status";

########END ELSE and END IF
fi

# increasing line number
line_number=$((line_number+1))

################CHECKING IF THERE ARE STILL MOUNT POINTS

# calling another function (above) to fill the mount point at this line number
mount_point=$(read_mount_point "$line_number")

########################################################

#:::::::::::ENDING OF MAIN LOOP
done

exit
}

refresh_initscripts() {

#calling the two functions that do the job
clean_initscripts
generate_initscripts

exit
}

print_status() {

#prints the status of all mounted folders

# initializing variables    
line_number=1
mount_type="tmpfs" #hardcoded for now

######################CHECKING IF THERE ARE STILL MOUNT POINTS

# calling another function (above) to fill the mount point at this line number
mount_point=$(read_mount_point "$line_number")

#########################################################

############BEGINNING MAIN LOOP::::::::::::::::::::::::::::::::::::::

until [ "$mount_point" = "no_more_mount_points" ] ;  do

# calling another function (above) to fill the mount point at this line number
mount_point=$(read_mount_point "$line_number")

# calling another function (above) to fill the initscript name at this line number
initscript_name=$(generate_initscript_name "$mount_point")

# generating a variable with full name inside, easier to manipulate
initscript_path="/etc/init.d/$initscript_name"

if [ -e "initscript_path" ]; then 
"$initscript_path" status >> "/run/print_status";
else
echo "no folder2ram init script found" >> "/run/print_status";
fi

# increasing line number
line_number=$((line_number+1))

################CHECKING IF THERE ARE STILL MOUNT POINTS

# calling another function (above) to fill the mount point at this line number
mount_point=$(read_mount_point "$line_number")

########################################################

#:::::::::::ENDING OF MAIN LOOP
done

}

configure(){

#if there is no config file it is generated from the template
if [ ! -e "/etc/folder2ram/folder2ram.conf" ]; then
cp "/etc/folder2ram/templates/folder2ram.conf" "/etc/folder2ram/folder2ram.conf" ;
fi

#will now ask for what text editor to use and then open it
echo "will now open the configuration file with your favourite text editor"
echo "write its name and press enter (nano, vim, gedit are the most common)"
read editor

"$editor" "/etc/folder2ram/folder2ram.conf" 

}

reset(){

#calling a function to do this job
clean_initscripts

#removing current config and making a new one from the template
rm -f "/etc/folder2ram/folder2ram.conf" 
cp "/etc/folder2ram/template/folder2ram.conf" "/etc/folder2ram/folder2ram.conf" 

exit

}

##################END FUNCTIONS ###########################

#force='false'
#quiet='false'
#all_mountpoints='false'

#doing a root check, because folder2ram must be run as root for obvious reasons
if [ "$(id -u)" -eq 0 ]; then
echo "good, running as root";
else
echo "you must run folder2ram as root, write sudo folder2ram or su folder2ram";
exit
fi

action="$1"
[ -z "$action" ] && print_usage_exit;

#shift

#while [ $# -gt 0 ]; do
#    case "$1" in
#        -a)
#            [ "$mountpoint" != "%%none%%" ] && print_usage_exit
#            mountpoint=""
#            ;;

#        -f)
#            force='true'
#            ;;

#        -q)
#            quiet='true'
#            ;;

#        *)
#            [ -z "$mountpoint" ] || [ "$mountpoint" != '%%none%%' ] && print_usage_exit
#            mountpoint="$1"
#            ;;
#    esac
#    shift
#done

#[ "$mountpoint" = "%%none%%" ] && print_usage_exit

case "$action" in
-generate)
        generate_initscripts
	cat "/run/print_status"
	rm -f "/run/print_status"
        ;;
-clean)
        clean_initscripts
	cat "/run/print_status"
	rm -f "/run/print_status"
        ;;
-refresh)
        refresh_initscripts
	cat "/run/print_status"
	rm -f "/run/print_status"
        ;;
-status)
        print_status
	cat "/run/print_status"
	rm -f "/run/print_status"
        ;;
-mount)
	read mountpoint        
	mount_umount_mountpoint "$mountpoint" start
	cat "/run/print_status"
	rm -f "/run/print_status"
        ;;
-mountall)
	mount_umount_all start
	cat "/run/print_status"
	rm -f "/run/print_status"
        ;;
-umount)
	read mountpoint
        mount_umount_mountpoint "$mountpoint" stop
	cat "/run/print_status"
	rm -f "/run/print_status"
        ;;
-umountall)
        mount_umount_all stop
	cat "/run/print_status"
	rm -f "/run/print_status"
        ;;
-configure)
        configure
        ;;
-reset)
        reset
        ;;
*)
        print_usage
        ;;
esac

rm -f "/run/print_status"
