#! /bin/sh

. /lib/folder2ram/unmount-scripts/common.sh

dir="$1"
shift
options="$*"

# Decode the options given in parameters
ignore_file_regexp=""
ignore_folder_regexp=""
for opt in $options; do
    case "$opt" in
        ignore_file=*)
            ignore_file_regexp=${opt#ignore_file=*}
            ;;
        ignore_folder=*)
            ignore_folder_regexp=${opt#ignore_folder=*}
            ;;
        *)
            ;;
    esac
done

generate_sh_header
generate_folder_structure "$dir" "$ignore_folder_regexp"
generate_file_structure "$dir" "$ignore_file_regexp"


