#! /bin/sh
# the core function of this script was written by mcortese in 2010
# in this webpage https://www.debian-administration.org/article/661/A_transient_/var/log
# webpage saved and available in docs folder

. /lib/folder2ram/unmount-scripts/common.sh

dir="$1"
shift
options="$*"

# Decode the options given in parameters
exclude_pattern=""
include_pattern="."
for opt in $options; do
    case "$opt" in
        exclude_pattern=*)
            exclude_pattern=${opt#exclude_pattern=*}
            ;;
        include_pattern=*)
            include_pattern=${opt#include_pattern=*}
            ;;
        *)
            ;;
    esac
done

generate_sh_header
#generate_file_content "$dir" "$include_pattern" "$exclude_pattern" 
#---original part disabled

#stop_transient_file_content() {
        # Return
        #   0 if transient log has been stopped
        #   1 if transient log was already stopped
        #   2 if transient log could not be stopped
        #   other if a failure occurred

#        [ -f /var/lock/transientlog.lock ] || return 1

        # Check if I am root
#        [ `id -u` -eq 0 ] || return 2

        # Merge back to permanent storage
        cp -rfup $dir -T /var/folder2ram/$dir

        umount -l $dir
        umount -l /var/folder2ram/$dir
#        rm -r /var/lock/transientlog.lock
        return 0
#}
