.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH FOLDER2RAM 8 "2015" "folder2ram"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
folder2ram \- automated tmpfs folder management
.SH SYNOPSIS
\fBfolder2ram\fP \fIaction\fP \fB\-generate\fP [\fB\-clean\fP] [\fB\-refresh\fP] [\fB\-status\fP] [\fB\-mountall\fP] [\fB\-mount\fP] [\fB\-umountall\fP] [\fB\-umountall\fP] [\fB\-configure\fP] [\fB\-reset\fP]
.PP
.SH DESCRIPTION
\fBfolder2ram\fP folder2ram is a script-based utility that relocates the contents of a folder 
to tmpfs (more options in the future) and on shutdown unmounts it safely synching the data back
to the permanent storage (more options about when and where to sync in the future).
\fBfolder2ram\fP is a configuration script that generates init scripts that then do the leg work
of mounting, unmounting and syncing. 

.SH OPTIONS
.TP
\fIaction\fP
This option specifies the action to execute. It could be :
.RS
.TP .4i
\fB-generate\fP:
read the configuration file at /etc/folder2ram/folder2ram.etc and generate the init scripts that are missing
.TP
\fB-clean\fP:
stop folder2ram and remove all folder2ram init scripts
.TP
\fB-refresh\fP:
execute a -clean followed by a -generate
.TP
\fB-status\fP:
print all mountpoints and their status (mounted or unmounted)
.TP
\fB-mountall\fP:
start all folder2ram initscripts
.TP
\fB-mount /folder/path\fP:
start the init script for that particular folder, if it is in the configuration file.
.TP
\fB\-umount /folder/path\fP
stop the init script for that particular folder, if it is in the configuration file.
.TP
\fB\-umountall\fP
folder2ram will stop all initscripts of all folders in the config file
.TP
\fB\-configure\fP
open the configuration file in a text editor
.TP
\fB\-reset\fP
delete all folder2ram init scripts and restore default config file
.SH DEFAULTS
By default, \fBfolder2ram\fP won't make /var/run, /var/lock or /tmp available as
ram filesystems. Since \fBsysvinit\fP provides a way to achieve this, it is
preferable to use it. See \fBtmpfs\fP(5) for more information.
.SH INIT SCRIPTS 
The init scripts are completely independent from the folder2ram configuration file and configuration script.
Each mount point has its own initscript. This tends to pollute a bit the init folder, but allows safer 
operation since if/when a script fails the others are unaffected.
.SH FILES
.PP
.IP "/etc/folder2ram/folder2ram.conf"
configuration file,
.IP "/sbin/folder2ram"
configuration script
.IP "/etc/folder2ram/templates/*"
here you find an init script template and a configuration file template, these are used by the configuration
script, any modification to the templates may have bad effects
.IP "/var/folder2ram/*"
here you will find the bind-mounted folders so you (and the init scripts) can access the original folder in permanent storage to sync the contents of the tmpfs  
.SH SEE ALSO
\fBmount\fP(8), \fBtmpfs\fP(5), \fBrcS\fP(5).
.SH AUTHOR
the author of folder2ram is Alberto Bursi <starshipeleven@hotmail.it>
