#! /bin/sh

. /lib/fs2ram/unmount-scripts/common.sh

dir="$1"
shift
options="$*"

# Decode the options given in parameters
ignore_folder_regexp=""
for opt in $options; do
    case "$opt" in
        ignore_folder=*)
            ignore_folder_regexp=${opt#ignore_folder=*}
            ;;
        *)
            ;;
    esac
done

generate_sh_header
generate_folder_structure "$dir" "$ignore_folder_regexp"


